// Auto-generated catalog of default consumables

List<Map<String, dynamic>> getDefaultConsumablesCatalog() {
  return [
    {
      'id': "cons_1",
      'name': "Firing Pin Diameter 1..52mm",
      'serial': "290105U",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_2",
      'name': "Firing Pin Diameter 1.98mm",
      'serial': "290106U",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_3",
      'name': "Firing Pin Spring",
      'serial': "290104U",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_4",
      'name': "Pre-Stressing Screw",
      'serial': "290204U",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_5",
      'name': "Adjusting Nut",
      'serial': "290205U",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_6",
      'name': "Fixing Nut",
      'serial': "290203U",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_7",
      'name': "Insulator",
      'serial': "290101U",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_8",
      'name': "Insulating Screw",
      'serial': "290102U",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_9",
      'name': "Fixing Pin",
      'serial': "290206U",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_10",
      'name': "Fixing Screw for cartridge extractor socket",
      'serial': "290501U",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_11",
      'name': "Set Screw",
      'serial': "290207U",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_12",
      'name': "Fixing Screw for firing Spring Bearing",
      'serial': "290202U",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_13",
      'name': "Buffer for firing pin diameter 1.52 mm(square)",
      'serial': "290311U",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_14",
      'name': "Buffer for firing pin diameter 1.98 mm(square)",
      'serial': "290312U",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_15",
      'name': "Einbauchse 16A, Polklemme, rot EU-0083",
      'serial': "EU-0083",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_16",
      'name': "Einbauchse 16A, Polklemme, schwarz EU-0082",
      'serial': "EU-0082",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_17",
      'name': "Diaphram Protection for GP2, GP6, GP8",
      'serial': "ZG-0307",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_18",
      'name': "GP6 Pressure Transducer Set",
      'serial': "GP6",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_19",
      'name': "GP8 Pressure Transducer Set",
      'serial': "GP8",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_20",
      'name': "Sealing Rings, GP2, GP6 & GP8",
      'serial': "Z3321",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_21",
      'name': "Finishing tool for re-work the sealing surface of pressure vent",
      'serial': "Z3108",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_22",
      'name': "E178-2 Piezo cable",
      'serial': "",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_23",
      'name': "B292-TC- Trigger Cable",
      'serial': "BV-0039",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_24",
      'name': "IP67 CLink to IP67 CLink, 9meters",
      'serial': "",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_25",
      'name': "B590 Netzkabel (Power cable)",
      'serial': "",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_26",
      'name': "Distance ring for locking lever screw",
      'serial': "290607U",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_27",
      'name': "Locking lever base part",
      'serial': "290604U",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_28",
      'name': "Handle for locking lever",
      'serial': "290603U",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_29",
      'name': "Locking lever screw",
      'serial': "290605U",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_30",
      'name': "Bolt",
      'serial': "290305U",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_31",
      'name': "Hinge pin",
      'serial': "290302U",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_32",
      'name': "Bolt return spring",
      'serial': "290306U",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_33",
      'name': "Extractor Body",
      'serial': "290512U",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_34",
      'name': "Trigger lever",
      'serial': "290304U",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_35",
      'name': "Tweezer antimagnetic",
      'serial': "",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_36",
      'name': "Head space gages 9x19 NATO",
      'serial': "2705B/9",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_37",
      'name': "Adjusting Ring Spanner",
      'serial': "290601",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_38",
      'name': "Adjusting Ring",
      'serial': "290406U",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_39",
      'name': "Allen Wrench Set",
      'serial': "",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_40",
      'name': "installation Tool Kit for GP-Series",
      'serial': "Z3206",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_41",
      'name': "B472-VK LAN Connection Cable",
      'serial': "B472-VK LAN",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_42",
      'name': "B472-TR Timer Recorder (LAN)",
      'serial': "B472-TR",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_43",
      'name': "292UR EPVAT Receiver",
      'serial': "292UR",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_44",
      'name': "B617 Muzzle Flash Detector Kit",
      'serial': "B617",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_45",
      'name': "B590 Ethernet-Kable",
      'serial': "",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_46",
      'name': "Extractor with positioning nose",
      'serial': "290515U",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_47",
      'name': "Extractor Spring",
      'serial': "290518U",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_48",
      'name': "Lead screw",
      'serial': "290503U",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_49",
      'name': "Assembly screw for fixing plate",
      'serial': "290411U",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_50",
      'name': "B472-MR Measuring frame",
      'serial': "B472-MR",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_51",
      'name': "Buffer spanner",
      'serial': "290602U",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_52",
      'name': "Breech block",
      'serial': "290301U",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_53",
      'name': "Electro-magnetic firing mechanism",
      'serial': "",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_54",
      'name': "Trigger bolt",
      'serial': "29U303",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_55",
      'name': "Hinge screw for trigger",
      'serial': "290309U",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_56",
      'name': "2922E EPVAT Test Barrel 5.56mm NATO 7\"",
      'serial': "2922E",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_57",
      'name': "2972BE Accuracy Test Barrel 5.56x45 NATO 7\"",
      'serial': "2972BE",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_58",
      'name': "2922E EPVAT Test Barrel 5.56mm MIL 12\"",
      'serial': "2922E",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_59",
      'name': "2972BE Accuracy Test Barrel 5.56x45 MIL 12\"",
      'serial': "2972BE",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_60",
      'name': "2972BE Accuracy Test Barrel .223 for .223 Rem9\"",
      'serial': "2972BE",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_61",
      'name': "2972BE EPVAT Test Barrel .223 for .223  C.I.P",
      'serial': "",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_62",
      'name': "2972BE Accuracy Test Barrel 9x19mm",
      'serial': "2972BE",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_63",
      'name': "2922E EPVAT Test Barrel 9mm NATO",
      'serial': "2922E",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_64",
      'name': "2922E EPVAT Test Barrel 7.62mm NATO",
      'serial': "",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_65",
      'name': "2922E Accuracy Test Barrel 7.62mm NATO",
      'serial': "",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_66",
      'name': "C.I.P Gas pressure Test Barrel 7.62mm .308",
      'serial': "",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_67",
      'name': "Accuracy Test Barrel 7.62mm .308",
      'serial': "",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_68",
      'name': "Cleaning Kit",
      'serial': "",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_69",
      'name': "Fixing Screw",
      'serial': "2905019U",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_70",
      'name': "Firing Pin Spring Bear",
      'serial': "290201U",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_71",
      'name': "Power Supply for camera",
      'serial': "EN-0037",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_72",
      'name': "Silicon grease",
      'serial': "YJ-0123",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_73",
      'name': "Reflector tape",
      'serial': "",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_74",
      'name': "Reflector tape holder",
      'serial': "",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_75",
      'name': "Calibartion Holder Device",
      'serial': "",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_76",
      'name': "5.56 GO/NOGO (NATO)",
      'serial': "TH02705B5A.01",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_77",
      'name': "7.62 GO/NOGO (NATO)",
      'serial': "TH02705B7A.01",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_78",
      'name': ".308 GO/NOGO (SAAMI)",
      'serial': "TH02705B0A.01",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_79",
      'name': "29061E Trigger magnet cable BV-0041 rev04",
      'serial': "29061E",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_80",
      'name': "550m Calibration device B590",
      'serial': "TH0590KALA.01",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_81",
      'name': "50m Calibration device B590",
      'serial': "TH0590KALA.01",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_82",
      'name': "Board of LED",
      'serial': "",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_83",
      'name': "LED light for optical target system",
      'serial': "",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_84",
      'name': "B617 Flash Detector Front Panel including Lens",
      'serial': "",
      'category': "Shooting System",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_85",
      'name': "Spare parts B180.1 Adapter",
      'serial': "",
      'category': "Closed Vessel and Calibration Unit",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_86",
      'name': "B180 Resistance Temp. Detector",
      'serial': "",
      'category': "Closed Vessel and Calibration Unit",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_87",
      'name': "Electrode 1",
      'serial': "YJ-6210",
      'category': "Closed Vessel and Calibration Unit",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_88",
      'name': "USB to RS485 Converter, 1-Port",
      'serial': "",
      'category': "Closed Vessel and Calibration Unit",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_89",
      'name': "USB Interface RS485 for PC's",
      'serial': "",
      'category': "Closed Vessel and Calibration Unit",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_90",
      'name': "National Instruments Type NI 778475-01",
      'serial': "",
      'category': "Closed Vessel and Calibration Unit",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_91",
      'name': "B630 Adapter for one Piezoelectric transducer",
      'serial': "B630",
      'category': "Closed Vessel and Calibration Unit",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_92",
      'name': "B630 Valve Body",
      'serial': "ZG0268",
      'category': "Closed Vessel and Calibration Unit",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_93",
      'name': "B630 Non Return Valve Body",
      'serial': "ZG-0276",
      'category': "Closed Vessel and Calibration Unit",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_94",
      'name': "B630 Rebound Seal",
      'serial': "ZG-0277",
      'category': "Closed Vessel and Calibration Unit",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_95",
      'name': "Sealing ring for 5QP",
      'serial': "Z3305",
      'category': "Closed Vessel and Calibration Unit",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_96",
      'name': "B630 Stop Ring",
      'serial': "ZG-0275",
      'category': "Closed Vessel and Calibration Unit",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_97",
      'name': "B630 Cu-Gasket 9,05mm",
      'serial': "ZG-0308",
      'category': "Closed Vessel and Calibration Unit",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_98",
      'name': "B630 Support Ring Short",
      'serial': "ZG-0232",
      'category': "Closed Vessel and Calibration Unit",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_99",
      'name': "B630 Plunger",
      'serial': "ZG-0236",
      'category': "Closed Vessel and Calibration Unit",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_100",
      'name': "B630 Retainer Screw",
      'serial': "ZG-0251",
      'category': "Closed Vessel and Calibration Unit",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_101",
      'name': "B630 Pressure Screw",
      'serial': "ZG-0235",
      'category': "Closed Vessel and Calibration Unit",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_102",
      'name': "B630 Anti Turn Locking Device",
      'serial': "ZG-0237",
      'category': "Closed Vessel and Calibration Unit",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_103",
      'name': "Double open wrench 22x24",
      'serial': "",
      'category': "Closed Vessel and Calibration Unit",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_104",
      'name': "B630 High Pressure Liquid",
      'serial': "",
      'category': "Closed Vessel and Calibration Unit",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_105",
      'name': "B630 Power Cable",
      'serial': "",
      'category': "Closed Vessel and Calibration Unit",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_106",
      'name': "USB 2.0 Cable A-B, 1,8m",
      'serial': "",
      'category': "Closed Vessel and Calibration Unit",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_107",
      'name': "B202-RC Reference Capacitor",
      'serial': "TH020RC-A.01",
      'category': "Closed Vessel and Calibration Unit",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_108",
      'name': "Electrode 2",
      'serial': "YJ-6211",
      'category': "Closed Vessel and Calibration Unit",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_109",
      'name': "Terminal Core",
      'serial': "YJ-0207",
      'category': "Closed Vessel and Calibration Unit",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_110",
      'name': "Insulating Cone",
      'serial': "YJ-0214",
      'category': "Closed Vessel and Calibration Unit",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_111",
      'name': "Spare parts B180.1 Valves",
      'serial': "TH01801SVA.01",
      'category': "Closed Vessel and Calibration Unit",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_112",
      'name': "PG HD Selaing Ring",
      'serial': "ZG-0213",
      'category': "Closed Vessel and Calibration Unit",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_113",
      'name': "Spare parts B180.1 Locking Piece",
      'serial': "TH01801SLA.01",
      'category': "Closed Vessel and Calibration Unit",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_114",
      'name': "B180.01 Pin wrench",
      'serial': "YJ-0360",
      'category': "Closed Vessel and Calibration Unit",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_115",
      'name': "B173 IG Iginition Cable, 3m",
      'serial': "BV-0048",
      'category': "Closed Vessel and Calibration Unit",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_116",
      'name': "5,56 Percutor pin",
      'serial': "",
      'category': "Primer Equipment",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_117",
      'name': "9 mm Percutor pin",
      'serial': "",
      'category': "Primer Equipment",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_118",
      'name': "Contact pushing spring",
      'serial': "",
      'category': "Primer Equipment",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_119",
      'name': "7.62 Percutor pin",
      'serial': "",
      'category': "Primer Equipment",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_120",
      'name': "Internal shock sensor",
      'serial': "",
      'category': "Primer Equipment",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_121",
      'name': "Primed Case Holder for 9mm",
      'serial': "",
      'category': "Primer Equipment",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_122",
      'name': "Primed Case Holder for 7.62",
      'serial': "",
      'category': "Primer Equipment",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_123",
      'name': "Primed Case Holder for 5.56",
      'serial': "",
      'category': "Primer Equipment",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_124",
      'name': "Regulation Position screw",
      'serial': "",
      'category': "Primer Equipment",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_125",
      'name': "Position Sensor",
      'serial': "",
      'category': "Primer Equipment",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_126",
      'name': "Dropping Ball weight 55 g",
      'serial': "",
      'category': "Primer Equipment",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_127",
      'name': "Dropping Ball weight 111.7 g",
      'serial': "",
      'category': "Primer Equipment",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_128",
      'name': "Competition powder measure",
      'serial': "",
      'category': "Residual Stress Items",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_129",
      'name': "charge master link electronic powder dispenser",
      'serial': "",
      'category': "Residual Stress Items",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_130",
      'name': "Universal hand priming tool (90201)",
      'serial': "",
      'category': "Residual Stress Items",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_131",
      'name': "Shell holder #10",
      'serial': "",
      'category': "Residual Stress Items",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_132",
      'name': "Shell holder #16",
      'serial': "",
      'category': "Residual Stress Items",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_133",
      'name': "Shell holder #3",
      'serial': "",
      'category': "Residual Stress Items",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_134",
      'name': "Universal case loading block",
      'serial': "",
      'category': "Residual Stress Items",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_135",
      'name': "Pocket scale 1500 GN",
      'serial': "",
      'category': "Residual Stress Items",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_136",
      'name': "Automatic priming tool",
      'serial': "",
      'category': "Residual Stress Items",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_137",
      'name': "Automatic primer tube",
      'serial': "",
      'category': "Residual Stress Items",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_138",
      'name': "Primer catcher",
      'serial': "",
      'category': "Residual Stress Items",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_139",
      'name': "Automatic primer feed combo",
      'serial': "",
      'category': "Residual Stress Items",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_140",
      'name': "Pro chucker 7 progressive reloading press",
      'serial': "",
      'category': "Residual Stress Items",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_141",
      'name': "Ultra Sonic Cleaner",
      'serial': "",
      'category': "Weapon Cleaning Items",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_142",
      'name': "weapon  cleaning solution (liters)",
      'serial': "",
      'category': "Weapon Cleaning Items",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "liters",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_143",
      'name': "Disscator Glass Adapter",
      'serial': "",
      'category': "Weapon Cleaning Items",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_144",
      'name': "Transformer",
      'serial': "",
      'category': "Weapon Cleaning Items",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_145",
      'name': "Barrel 508mm",
      'serial': "1240010401E",
      'category': "Steyr Rifle Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_146",
      'name': "Regulator gas complete",
      'serial': "1200010460",
      'category': "Steyr Rifle Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_147",
      'name': "Grip barrel Sub Assy 7013",
      'serial': "1200010490",
      'category': "Steyr Rifle Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_148",
      'name': "LID, grip barrel 7013",
      'serial': "1200010071",
      'category': "Steyr Rifle Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_149",
      'name': "Spring, Grip Barrel",
      'serial': "1200010071",
      'category': "Steyr Rifle Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_150",
      'name': "Pin, Retaining grip barrel",
      'serial': "1200010078",
      'category': "Steyr Rifle Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_151",
      'name': "Eliminator flash A3",
      'serial': "1252010012",
      'category': "Steyr Rifle Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_152",
      'name': "NUT AUG A3",
      'serial': "1250010039",
      'category': "Steyr Rifle Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_153",
      'name': "Piston",
      'serial': "1200010050",
      'category': "Steyr Rifle Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_154",
      'name': "Ring, Piston",
      'serial': "1200010051H",
      'category': "Steyr Rifle Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_155",
      'name': "Spring piston",
      'serial': "1200010052",
      'category': "Steyr Rifle Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_156",
      'name': "Bayonet holder",
      'serial': "1200090530",
      'category': "Steyr Rifle Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_157",
      'name': "NUT",
      'serial': "3870203",
      'category': "Steyr Rifle Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_158",
      'name': "Screw",
      'serial': "3862094",
      'category': "Steyr Rifle Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_159",
      'name': "Washer",
      'serial': "3936610",
      'category': "Steyr Rifle Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_160",
      'name': "Slide, SUB-ASSY.",
      'serial': "1200040406",
      'category': "Steyr Rifle Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_161",
      'name': "Plunger, Spring Lock Long",
      'serial': "1200040025",
      'category': "Steyr Rifle Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_162",
      'name': "Spring, Lock long",
      'serial': "1200040026",
      'category': "Steyr Rifle Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_163",
      'name': "Spring, Lock short",
      'serial': "1200040027",
      'category': "Steyr Rifle Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_164",
      'name': "ROD compensating",
      'serial': "1200040028",
      'category': "Steyr Rifle Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_165",
      'name': "Thrust piece , left",
      'serial': "1200040031H",
      'category': "Steyr Rifle Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_166",
      'name': "Thrust piece , right",
      'serial': "1200040030",
      'category': "Steyr Rifle Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_167",
      'name': "Bolt, right",
      'serial': "1200040570E",
      'category': "Steyr Rifle Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_168",
      'name': "Bolt, left",
      'serial': "1200040572E",
      'category': "Steyr Rifle Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_169",
      'name': "Extractor",
      'serial': "1200040042",
      'category': "Steyr Rifle Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_170",
      'name': "Pin, Extractor",
      'serial': "1200040037",
      'category': "Steyr Rifle Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_171",
      'name': "Spring, Extractor SUB-ASSY",
      'serial': "1200040438",
      'category': "Steyr Rifle Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_172",
      'name': "Ejector",
      'serial': "1200040045",
      'category': "Steyr Rifle Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_173",
      'name': "Spring, Ejector",
      'serial': "1200040046",
      'category': "Steyr Rifle Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_174",
      'name': "PIN, Retaining Ejector",
      'serial': "3909598",
      'category': "Steyr Rifle Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_175",
      'name': "Slide locking",
      'serial': "1200040063",
      'category': "Steyr Rifle Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_176",
      'name': "Pin, control",
      'serial': "1200040061",
      'category': "Steyr Rifle Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_177",
      'name': "Spring, slide locking",
      'serial': "1200040083",
      'category': "Steyr Rifle Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_178",
      'name': "Pin, retaining, pin control",
      'serial': "3909682",
      'category': "Steyr Rifle Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_179",
      'name': "Roller, slide",
      'serial': "1200040005",
      'category': "Steyr Rifle Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_180",
      'name': "Pin, Roller slide",
      'serial': "3900000",
      'category': "Steyr Rifle Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_181",
      'name': "Pin, firing spring loaded, SUB-ASSY",
      'serial': "1200040590",
      'category': "Steyr Rifle Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_182",
      'name': "Sleeve, spring slide locking",
      'serial': "1200040097",
      'category': "Steyr Rifle Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_183",
      'name': "Cocking-piece, Anti turn device",
      'serial': "1200040110",
      'category': "Steyr Rifle Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_184",
      'name': "Ant-turn device",
      'serial': "1200040120",
      'category': "Steyr Rifle Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_185",
      'name': "Pin",
      'serial': "3900344",
      'category': "Steyr Rifle Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_186",
      'name': "LID Ejection, inside",
      'serial': "1200060010",
      'category': "Steyr Rifle Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_187",
      'name': "LID Ejection, outside, olive 7013",
      'serial': "1200060011",
      'category': "Steyr Rifle Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_188",
      'name': "Replacement Barrel and Front Sight Assembly",
      'serial': "402756",
      'category': "M16 & M4 Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_189",
      'name': "Upper Receiver Assembly",
      'serial': "63528",
      'category': "M16 & M4 Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_190",
      'name': "Handguard Assembly",
      'serial': "64508",
      'category': "M16 & M4 Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_191",
      'name': "Gas Tube Assembly",
      'serial': "61645",
      'category': "M16 & M4 Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_192",
      'name': "Barrel and Front Sight Assembly",
      'serial': "402799",
      'category': "M16 & M4 Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_193",
      'name': "Crush Washer",
      'serial': "12991533",
      'category': "M16 & M4 Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_194",
      'name': "Compensator",
      'serial': "64502",
      'category': "M16 & M4 Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_195",
      'name': "Handguard Retaining Ring",
      'serial': "90403",
      'category': "M16 & M4 Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_196",
      'name': "Spring Weld Assembly",
      'serial': "61962",
      'category': "M16 & M4 Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_197",
      'name': "Handguard Slip Ring",
      'serial': "62482",
      'category': "M16 & M4 Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_198",
      'name': "Gas Tube Roll Pin",
      'serial': "95108",
      'category': "M16 & M4 Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_199",
      'name': "Retaining Ring, Ejection Port Cover Hinge",
      'serial': "90402",
      'category': "M16 & M4 Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_200",
      'name': "Cover Hinge Pin",
      'serial': "61658",
      'category': "M16 & M4 Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_201",
      'name': "Ejection Port Cover Assembly",
      'serial': "64532",
      'category': "M16 & M4 Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_202",
      'name': "Ejection Port Cover Spring",
      'serial': "8448532",
      'category': "M16 & M4 Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_203",
      'name': "Plunger Spring",
      'serial': "62271",
      'category': "M16 & M4 Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_204",
      'name': "Forward Assist Assembly",
      'serial': "64543",
      'category': "M16 & M4 Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_205",
      'name': "Firing Pin",
      'serial': "62294",
      'category': "M16 & M4 Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_206",
      'name': "Firing Pin Retaining Pin",
      'serial': "62335",
      'category': "M16 & M4 Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_207",
      'name': "Cam Pin",
      'serial': "8448502",
      'category': "M16 & M4 Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_208",
      'name': "Key and Bolt Carrier Assembly",
      'serial': "62286",
      'category': "M16 & M4 Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_209",
      'name': "Bolt Ring",
      'serial': "61540",
      'category': "M16 & M4 Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_210",
      'name': "Bolt",
      'serial': "61538",
      'category': "M16 & M4 Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_211",
      'name': "Extractor Pin",
      'serial': "8448513",
      'category': "M16 & M4 Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_212",
      'name': "Ejector Spring Pin",
      'serial': "95102",
      'category': "M16 & M4 Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_213",
      'name': "Ejector Spring",
      'serial': "8448516",
      'category': "M16 & M4 Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_214",
      'name': "Ejector",
      'serial': "8448515",
      'category': "M16 & M4 Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_215",
      'name': "Extractor",
      'serial': "61562",
      'category': "M16 & M4 Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_216",
      'name': "Extractor Spring Assembly",
      'serial': "64026",
      'category': "M16 & M4 Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_217",
      'name': "Upper Receiver and Barrel Assembly",
      'serial': "402738",
      'category': "M16 & M4 Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_218",
      'name': "Handguard Assembly",
      'serial': "64673",
      'category': "M16 & M4 Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_219",
      'name': "Gas Tube Assembly",
      'serial': "62366",
      'category': "M16 & M4 Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
    {
      'id': "cons_220",
      'name': "Barrel and Front Sight Assembly",
      'serial': "65083",
      'category': "M16 & M4 Spare Parts",
      'quantity': 0,
      'minSafeThreshold': 0,
      'unit': "pcs",
      'supplier': '',
      'location': '',
      'imageBase64': '',
      'history': <Map<String, dynamic>>[],
    },
  ];
}
